### ISSUE TITLE
Dark Mode and Font colors

### ISSUE THREAD

**Issue by yehiasalam** [hediet/vscode-drawio#217]
Hi,

I don't think it's an issue, but i am not sure whats the proper configuration to handle this case.
 
So I have the vscode and the extension running in dark mode, and I created a diagram as below:

![s1](https://user-images.githubusercontent.com/201734/114265664-6b85d380-99f2-11eb-8bf0-4f20f2e49f32.jpg)

The problem is whenever I embedded to a markdown file. I look like this:

![s2](https://user-images.githubusercontent.com/201734/114265673-7d677680-99f2-11eb-80f9-5e1233b2b09c.jpg)

Not sure how to set this right?

**Comment by hediet** [comment]
The extension always uses the light theme to export diagrams to svg!
Otherwise it would look aweful e.g. when embedded in github readmes.

I don't think it is even possible to create colored transparent svg documents that look great on light and dark themes.

I think you can set a background color or set explicit colors that are theme-independent.

**Comment by pauloch8** [comment]
For me it would be better to the embedded drawio aways be in light theme. 
I think would be better if it was configurable to drawio assume the color theme of vscode or be always light (the original drawio app color).

**Comment by generateui** [comment]
We're using the extension to create `.drawio.svg` files. They contain source diagram xml and render to images when included in markdown files. This is great, as it keeps the sources in one file and **always synced**.

We had the same problem too, that the editor is cool by supporting a dark vscode theme, but the rendering breaks down when included on rendered markdown (html) pages. White text on white backgrounds, blank lines on dark backgrounds, those kind of things.

I have solved this by
1. Rendering all `.drawio.svg` files inline (as opposed to `<img src="graph.drawio.svg">`
2. Adding a css stylesheet with a media query `@media (prefers-color-scheme: dark)` and overriding some styles on svg elements:
```css
	rect:not([stroke="none"]) {
		/* show rect having white border */
		stroke:rgb(255, 255, 255) !important;
		/* render all backgrounds completely transparent */
		fill-opacity: 0;
	}
	svg div {
		color: rgb(255, 255, 255) !important;
	}
	path {
		stroke: rgb(255, 255, 255) !important;
	}
```
